[Launch]
AppName=Cisco Packet Tracer Portable
ProgramExecutable=Cisco_Packet_Tracer\bin\PacketTracer.exe
WorkingDirectory=Cisco_Packet_Tracer\bin
DirectoryCopyKeep=true
NoNetwork=true

[Activate]
Registry=true

[RegistryKeys]
CiscoPacketTracer=HKCU\Software\Cisco\Packet Tracer

[RegistryValueWrite]
; Sets the environmental home path inside standard user registry hive
HKCU\Environment\PT8HOME=REG_SZ:%PAL:AppDir%

; Non-Admin File Associations (Maps Extensions to the Local User Hive)
HKCU\Software\Classes\.pkt=REG_SZ:PacketTracer8
HKCU\Software\Classes\.pka=REG_SZ:PacketTracer8.Activity
HKCU\Software\Classes\.pkz=REG_SZ:PacketTracer8.PKZ
HKCU\Software\Classes\.pks=REG_SZ:PacketTracer8.ActivitySequence
HKCU\Software\Classes\.pksz=REG_SZ:PacketTracer8.ActivitySequencePackage

; Executable and Icon associations running out of standard user hive
HKCU\Software\Classes\PacketTracer8=REG_SZ:Cisco Packet Tracer
HKCU\Software\Classes\PacketTracer8\DefaultIcon=REG_SZ:%PAL:AppDir%\Cisco_Packet_Tracer\art\pkt.ico
HKCU\Software\Classes\PacketTracer8\shell\open\command=REG_SZ:"%PAL:AppDir%\Cisco_Packet_Tracer\bin\PacketTracer.exe" "%%1"

HKCU\Software\Classes\PacketTracer8.Activity=REG_SZ:Cisco Packet Tracer
HKCU\Software\Classes\PacketTracer8.Activity\DefaultIcon=REG_SZ:%PAL:AppDir%\Cisco_Packet_Tracer\art\pka.ico
HKCU\Software\Classes\PacketTracer8.Activity\shell\open\command=REG_SZ:"%PAL:AppDir%\Cisco_Packet_Tracer\bin\PacketTracer.exe" "%%1"

HKCU\Software\Classes\PacketTracer8.PKZ=REG_SZ:Cisco Packet Tracer
HKCU\Software\Classes\PacketTracer8.PKZ\DefaultIcon=REG_SZ:%PAL:AppDir%\Cisco_Packet_Tracer\art\pkz.ico
HKCU\Software\Classes\PacketTracer8.PKZ\shell\open\command=REG_SZ:"%PAL:AppDir%\Cisco_Packet_Tracer\bin\PacketTracer.exe" "%%1"

HKCU\Software\Classes\PacketTracer8.ActivitySequence=REG_SZ:Cisco Packet Tracer
HKCU\Software\Classes\PacketTracer8.ActivitySequence\DefaultIcon=REG_SZ:%PAL:AppDir%\Cisco_Packet_Tracer\art\pkz.ico
HKCU\Software\Classes\PacketTracer8.ActivitySequence\shell\open\command=REG_SZ:"%PAL:AppDir%\Cisco_Packet_Tracer\bin\PacketTracer.exe" "%%1"

HKCU\Software\Classes\PacketTracer8.ActivitySequencePackage=REG_SZ:Cisco Packet Tracer
HKCU\Software\Classes\PacketTracer8.ActivitySequencePackage\DefaultIcon=REG_SZ:%PAL:AppDir%\Cisco_Packet_Tracer\art\pkz.ico
HKCU\Software\Classes\PacketTracer8.ActivitySequencePackage\shell\open\command=REG_SZ:"%PAL:AppDir%\Cisco_Packet_Tracer\bin\PacketTracer.exe" "%%1"

; Custom URL Protocol Association (PTTP URL Scheme)
HKCU\Software\Classes\pttp=REG_SZ:URL:pttp
HKCU\Software\Classes\pttp\URL Protocol=REG_SZ:
HKCU\Software\Classes\pttp\shell\open\command=REG_SZ:"%PAL:AppDir%\Cisco_Packet_Tracer\bin\PacketTracer.exe" -uri="%%1"

[FilesMove]
Cisco_Packet_Tracer=%APPDATA%\Cisco\Packet Tracer

[DirectoriesMove]
Cisco_Packet_Tracer_Files=%USERPROFILE%\Cisco_Packet_Tracer

[Environment]
PT8HOME=%PAL:AppDir%
DISABLE_WEBVIEW=1
QT_LOGGING_RULES=*.debug=false

[QtKeysCleanup]
QtKeys=HKCU\Software\Trolltech
